### PR TITLE
Credential-based authentication to protect public deployments from incurring unauthenticated API costs

### PR DESCRIPTION
**Pull request by jondwillis**
- [x] Simple credential-based (username + password) auth with NextAuth **to protect against incurring API usage costs with public deployments where OPENAI_API_KEY is set as an environment variable.**
- [x] Fix logic for not showing UI/protecting the API when AUTH_TYPE is not set
- [ ] Add to Settings UI (?)
- [x] Update README

### CODE REVIEW

**Comment by enricoros** [comment]
This is looking good. Please make sure that for existing developers and users there's no change of DX/UX, and I'm very glad to merge it. Extra kudos if you can write (or gpt4 can write) a /docs/with-authentication.md (or something similar) to explain how to turn this on (just environment, no source changes)

**Comment by jondwillis** [comment]
> This is looking good. Please make sure that for existing developers and users there's no change of DX/UX, and I'm very glad to merge it. Extra kudos if you can write (or gpt4 can write) a /docs/with-authentication.md (or something similar) to explain how to turn this on (just environment, no source changes)

Yep, that is the intent. I'll double check before taking this out of draft. Also, definitely gotta update docs.

**Comment by enricoros** [comment]
Hi @jondwillis, this is going well. I've just tried the patch on top of `main`, by quickly merging the conflicts.

I get the following when I just `next dev` and open localhost:3000:
image
Console:
image

Let me know when you are done with the patch, and I'll work to productize it. The merge will be simple, but if I apply the project code style there will be a few semicolons inserted in /lib/auth.ts - simple stuff, but if you're making changes, my merge will create conflicts, so _let me know when you're done_.

Quick question - why the [...nextauth] had to be renamed to JS again?

**Comment by enricoros** [comment]
@jondwillis I've merged, tested, added conditionals, and works for me, both with and without auth.
I've created this single commit on top of `main` so the latest and greatest is in.

Pushed for you to take a look, on the `https://github.com/enricoros/nextjs-chatgpt-app/compare/main...testing-feature-auth` branch. (single commit, squashed, I'll delete it before merging this). You can take a look and see if there's any code to change on yours.

**Comment by enricoros** [comment]
> Looks fantastic, love the comments and cleanup. I pushed some small changes to my branch (force pushed again), mainly for a hanging auth callback in some situations.

This is good. Auth is a good feature. It's a big impact, but I'm happy to merge. Here's the proposal: would you like me to perform a merge so that your feature is on top of main?

I can merge this pull request and adapt it for minimal impact to people that are deploying it now. Then you can re-start developing on top of 'main', so no code conflicts going forward.

Just let me know, and I'll perform the merge/adaptation of this PR.

**Comment by jondwillis** [comment]
> > Looks fantastic, love the comments and cleanup. I pushed some small changes to my branch (force pushed again), mainly for a hanging auth callback in some situations.
> 
> This is good. Auth is a good feature. It's a big impact, but I'm happy to merge. Here's the proposal: would you like me to perform a merge so that your feature is on top of main?
> 
> I can merge this pull request and adapt it for minimal impact to people that are deploying it now. Then you can re-start developing on top of 'main', so no code conflicts going forward.
> 
> Just let me know, and I'll perform the merge/adaptation of this PR.

That would be great. It's your project and I think you have a better idea what would be appropriate -- also hit me up on discord @ kuluu-jon#7990 -- would love to discuss the project more in-depth.

**Comment by enricoros** [comment]
Merged into variant-authentication (over the latest main).

**Pull request closed without merging**
