### PR TITLE
Integrating OpenAI Embeddings with Pinecone Database

### PR DESCRIPTION
**Pull request by argen666**
Hello,

I have added a feature to big-agi that integrates OpenAI embeddings with Pinecone, a vector database service. This feature leverages the power of semantic search by making it possible to store and retrieve OpenAI embeddings efficiently. This will improve the AI's ability to understand and generate responses based on the semantic meaning of the input.

Details:

Added Settings panel for Embeddings and Pinecone configuration
Integrated this service with the existing AI functionality of the app. Embeddings mode can be activated by double click on the Chat button
The new feature adheres to the current tech stack of the project, i.e., Next.js and React.

Please review my changes. I would appreciate any feedback.

Thank you!

### CODE REVIEW

**Comment by argen666** [comment]
Moving forward, I propose the following enhancements:

**Implement a feature to upload documents to the vector database through the existing UI.**
This will make it easier for users to contribute their documents to the database and improve the AI's understanding and response generation.

**Add support for other vector databases recommended by OpenAI.** 
This will make the application more flexible and capable of handling different types of vector databases, thus expanding its usability and effectiveness.
[Recommended databases](https://platform.openai.com/docs/guides/embeddings/how-can-i-retrieve-k-nearest-embedding-vectors-quickly)

**Comment by rossman22590** [comment]
@argen666  does this work right now?

**Comment by argen666** [comment]
> @argen666 does this work right now?

yes, just set up your Pinecone API key and try

**Comment by rossman22590** [comment]
Going to try !

**Comment by peperunas** [comment]
Thank you @argen666 for the PR! As a newbie, I have a few questions though:

- Assuming the index has to be created beforehand on Pinecone, what are the dimensions needed for the index?
- Does the index need to be populated beforehand with data? If not, what is the difference between a vanilla LLM interaction and one with a vector database?

Also, I receive this error after setting up my API key and using the feature:

image

What am I doing wrong? 

Thank you again!

**Comment by argen666** [comment]
> Thank you @argen666 for the PR! As a newbie, I have a few questions though:
> 
> * Assuming the index has to be created beforehand on Pinecone, what are the dimensions needed for the index?
> * Does the index need to be populated beforehand with data? If not, what is the difference between a vanilla LLM interaction and one with a vector database?
> 
> Also, I receive this error after setting up my API key and using the feature:
> 
> image
> What am I doing wrong?
> 
> Thank you again!
Hi @peperunas , yes you need to create and populate the index first. Index dimension 1536. Thanks

**Comment by CyberRide** [comment]
is there a way this can be implemented with mogodb?

**Comment by argen666** [comment]
> is there a way this can be implemented with mogodb?

@CyberRide yep, I have a plan to implement it in the next PR :)

**Comment by argen666** [comment]
Hi @psociety, I have a plan to implement all supported index storages in the next PR :)

**Pull request closed without merging**
