### PR TITLE
Add support Kubernetes deployment

### PR DESCRIPTION
**Pull request by pichuang**
- Add Kubernetes Namespace / Deployment / Service (ClusterIP only)
- Add Secret for sensitive data

### CODE REVIEW

**Comment by pichuang** [comment]
image

```bash
$ kubectl -n big-agi get svc,pod,deployment
NAME              TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/big-agi   ClusterIP   10.0.198.118   <none>        3000/TCP   63m

NAME                          READY   STATUS    RESTARTS   AGE
pod/big-agi-d4f5d8b7b-jzvq4   1/1     Running   0          39m

NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/big-agi   1/1     1            1           63m

$ kubectl -n big-agi port-forward service/big-agi 3000
Forwarding from 127.0.0.1:3000 -> 3000
Forwarding from [::1]:3000 -> 3000
```

**Comment by enricoros** [comment]
@pichuang there's a file called `env-secrert.yaml` - is secre**R**t a typo, or is it like k8s does?

I will pull this PR in with one requirement - can you add a [docs/deploy-k8s.md](docs/deploy-k8s.md) file to explain how this works? We have "deploy-docker" and "deploy-couldflare" to explain those, and would love something along those lines.

Thanks for this first contribution!

**Comment by pichuang** [comment]
@enricoros Thank for the feedback, I've added your request to the latest commit.

**Comment by enricoros** [comment]
@pichuang I have two questions for this.

1. Who's using that Secrets Yaml file? I'm asking because we have a similar file called .env.example and would like to use only one of them (and eventually generate the other)

2. Is k8s building the container? If not, many of the runtime Env variables were not present at build time (when the UI is built), and the UI will ask for Keys even if the server (at runtime) has them.

Thanks in advance.

**Comment by PylotLight** [comment]
@pichuang Any updates here? I've deployed on k8s myself by exporting the helm config, but having these docs would have been helpful.

**Comment by enricoros** [comment]
Hi @PylotLight I don't have the knowledge to understand if this change is correct, clean and high-quality or not. What's your feedback?

**Comment by PylotLight** [comment]
> Hi @PylotLight I don't have the knowledge to understand if this change is correct, clean and high-quality or not. What's your feedback?

I read through it to review it and have some follow up questions. It looks good for the most part aside from a few documentation questions but otherwise should be fine.

**Comment by enricoros** [comment]
> I read through it to review it and have some follow up questions. It looks good for the most part aside from a few documentation questions but otherwise should be fine.

Can I merge it despite the questions, and what are the questions?

**Comment by PylotLight** [comment]
> > I read through it to review it and have some follow up questions. It looks good for the most part aside from a few documentation questions but otherwise should be fine.
> 
> Can I merge it despite the questions, and what are the questions?

May as well, its better than nothing, I can submit new PR to fix if needed.

**Pull request merged**
