### PR TITLE
[How-To] Add basic auth

### PR DESCRIPTION
**Pull request by LennardSchwarz**
For everyone who wants to deploy to Vercel but does not pay for premium features like basic auth, here a little template on how to add basic auth via nextJS middleware.

I normally program in python and have no idea about nextJS, so any feedback is more than welcome. For example, if I am protecting all the relevant pages in my middleware config.

### CODE REVIEW

**Comment by enricoros** [comment]
Hi @LennardSchwarz, I'm thinking of merging this. A couple of questions:

 - do you think the API routes should be authed as well? I don't know if they're authed or not, but this will prevent someone just using the backend. But I leave it to your expertise here
 - do know if this feature can be added without adding the api/auth/auth.ts function? maybe headers can be returned by the middleware, 'centralizing' this feature
 - the changes to the README would delete the existing README, so cannot be merged

**Comment by LennardSchwarz** [comment]
Hey @enricoros,

I am glad that you think this feature adds value!

This feature definitely needs more work before it can get added though. I honestly just blindly copied a couple of pieces of code I found without having much understanding of how nextJS or your application work:

https://stackoverflow.com/questions/64316886/how-do-i-add-basic-authentication-to-nextjs-node-server
https://github.com/vercel/examples/tree/main/edge-middleware/basic-auth-password

Regarding your questions:

1.  Yes, the API routes should definitely also be covered. There is a more sophisticed matcher option for the routes I have not looked into to make this more dynamic as well
2. The auth functionality is a middleware call. I think this can definitely merged with other middleware functionality you already have
3. I think it makes more sense fore you to add this feature via your own feature branch and then close this PR. I do not know enough NextJS to do this myself well

Acceptance criteria for this feature in my opinion:
- Basic auth should cover all routes which could be used to incur costs (i.e. calling third party APIs) or expose any private information (i.e chat messages, etc.)
- It should be possible to disable basic auth, i.e. by not providing env vars for username and password

I appreciate your work with this!

**Comment by enricoros** [comment]
Thanks @LennardSchwarz - I've merged, tested and documented.

By default, the auth is off (see docs/deploy-authentication.md), and the user will need to:
 - Rename `middleware_BASIC_AUTH.ts` to `middleware_BASIC_AUTH.ts`
 - Build the app
 - Set the env vars `HTTP_BASIC_AUTH_USERNAME` and `HTTP_BASIC_AUTH_PASSWORD`
 - Start the application/container

Thanks again!

**Comment by LennardSchwarz** [comment]
@enricoros: Thanks for the shoutout and your work!

I hope this project and your business plan behind it thrive.

**Pull request merged**
