### PR TITLE
[BUG] Fixes text on AI Personas Creator panel

### PR DESCRIPTION
**Pull request by therippa**
Small fix for https://github.com/enricoros/big-AGI/issues/548

image

image

### CODE REVIEW

**Comment by enricoros** [comment]
Thanks @therippa ! Is it working? I can't test it right now, but looks like the react hook is missing a dependency (potentially), which means it may not switch text when you switch tab. Is the behavior correct? (Or you can drag the file into big agi and ask :)

**Comment by therippa** [comment]
@enricoros - it's working as expected
big-agi

**Review by enricoros — APPROVED** [review]
Reviewed, made small changes to stabilize the react function (dependency was missing in the chain creation hook).

**Comment by enricoros** [comment]
@therippa merged. Performed smaller changes due to non trivial react hook dependencies.
Thanks for the contrib.
https://github.com/enricoros/big-AGI/commit/3a44f70db98b79376c0d718da9c4d71e63fcf207

**Pull request merged**
