### PR TITLE
feat: implement deepseek vendor

### PR DESCRIPTION
**Pull request by mapringg**
**Integrate Deepseek for Enhanced Messaging Capabilities**

This pull request introduces the integration of Deepseek. I have successfully verified the following functionalities:

| Functionality | Status |
| --- | --- |
| Adding messages | ✅ |
| Listing messages | ✅ |
| Sending messages | ✅ |

I have chosen to utilize fixed models due to the sparse details offered by the listing api. Please feel free to express concerns, and I will be happy to address them.

### CODE REVIEW

**Comment by enricoros** [comment]
Merged - tested, confirmed it works.
image

**Comment by enricoros** [comment]
@mapringg I've added a cleanup commit to make sure the models are discovered dynamically from the models endpoint, and reodered deepseek alphabetically in all the functions where it's used. Thanks for doing this.

Available right now on `main` to developers, but will be released more broadly in the next stable release (don't know the date yet, will be weeks)

**Comment by mapringg** [comment]
@enricoros Thanks for merging the PR. Looking forward to the next stable release.

**Comment by enricoros** [comment]
@mapringg in the meantime, the `main` branch is published on https://next.big-agi.com/ at every commit, so you can use it there - but will be deployed to the official get.big-agi.com on the next stable. Keep in mind the next stable will be Big-AGI 2.0.0.

**Review by enricoros — COMMENTED** [review]
👍

**Pull request merged**
