### PR TITLE
Use ctrl and remove alt usage with certain hotkeys for mac shortcuts

### PR DESCRIPTION
**Pull request by mapringg**
Fix broken shortcuts on mac devices. All hotkeys are now working properly. Before merging, I'd love to get feedback on this implementation. Please review and provide your thoughts on the adjustment I made.

### CODE REVIEW

**Comment by enricoros** [comment]
> Fix broken shortcuts on mac devices. All hotkeys are now working properly. Before merging, I'd love to get feedback on this implementation. Please review and provide your thoughts on the adjustment I made.

Thanks! I love it that you followed up on this. Indeed shortcuts have been broken for the longest time on Mac.

Feedback, as requested:

- The new implementation uses only Ctrl and not Cmd; before I thought that on Mac the "Cmd" (⌘) key would be go-to, and Ctrl is not used (someone commented on that before). From a user perspective, on web applications and desktop applications, what would be the most reasonable shortcuts (for opening a new chat for instance)?

- The checks for "isMacUser ? false : true" can be replaced with "!isMacUser", for brevity, but not required

- I wonder if there's a way to not change the shortcuts definitions, but simply ignore all the "Alt" (option) keys on Mac instead; in that case, the changes to AppChat may not be needed, simply the 'alt' flag would have 'altOnPC" semantics

- There is another function, for single-shortcut handling in useGlobalShortcuts, and may get the same treatment as the multi-shortcuts function, as it has the 'isCtrlOrCmd' treatment. Options could be: 1. actually remove the single-shortcut function and replace it with the multi-shortcuts function where needed (as the two functions do the same, which is a duplication), 2. update the single-shortcut function too

In essence, please let me know if the new shortcuts on Mac are consistent with the user expectations for opening a new chat in other web/apps, and if the requirement for Alt (Option) can be completely dropped on Mac, in which case, it can be checked at the shortcuts function, and no need to replace elsewhere.

**Comment by enricoros** [comment]
@mapringg lmk if you got the feedback and your answers, so I know how to merge

**Comment by mapringg** [comment]
- On Mac, the Cmd key is often a suitable choice for shortcuts. However, within a browser, it conflicts with numerous existing shortcuts. To maintain consistency across platforms, I propose adjusting the modifier key instead of changing the shortcut keys themselves. Specifically, replacing "Cmd" with "Ctrl" achieves this goal.

- I think it is possible to ignore all the Alt keys only for Mac users.

- I prefer replacing useGlobalShortcut with useGlobalShortcuts to avoid code duplication. Do you also wish for me to update the filename to reflect the change.

**Comment by enricoros** [comment]
@mapringg great directions, and approved (even file name change)

**Comment by mapringg** [comment]
I've worked on the fixes we discussed earlier. Please take a look at the updated code and let me know if everything looks good to you.

**Comment by mapringg** [comment]
I made a mistake and close the pull request while cleaning up.

**Comment by enricoros** [comment]
@mapringg Merged into `main` thanks again for the great work~!

**Comment by enricoros** [comment]
@mapringg I was thinking of cleaning up the shortcuts to have a somewhat more intuitive and productive mapping; are you open to this? 

This is the table I had in mind:
| Shortcut                                | Description                                     | Change |
|-----------------------------------------|-------------------------------------------------|--------|
| **Edit**                                |                                                 |        |
| Shift + Enter                           | Newline                                         | No change |
| Alt + Enter                             | Append (no response)                            | No change |
| Ctrl + Shift + B                                | **Beam** last message                           | No change |
| Ctrl + Shift + G                                | Re**Generate** last message                     | Changed from Ctrl + Shift + R |
| Ctrl + Shift + V                        | Attach clipboard (better than Ctrl + V)         | No change |
| Ctrl + M                                | Microphone (voice typing)                       | No change |
| **Chats**                               |                                                 |        |
| Ctrl + O                                | Open Chat ...                                   | No change |
| Ctrl + S                                | Save Chat ...                                   | No change |
| Ctrl + Shift + N                        | **New** chat                                    | Changed from Ctrl + Alt + N (Windows) / Ctrl + N (Mac) |
| Ctrl + Shift + X                        | **Reset** chat                                  | Changed from Ctrl + Alt + X (Windows) / Ctrl + X (Mac) |
| Ctrl + Shift + D                        | **Delete** chat                                 | Changed from Ctrl + Alt + D (Windows) / Ctrl + D (Mac) |
| (Removed)                               | **Branch** chat                                 | REMOVE |
| Ctrl + [                                | **Previous** chat (in history)                  | Changed from Ctrl + Alt + Left / (broken Mac) |
| Ctrl + ]                                | **Next** chat (in history)                      | Changed from Ctrl + Alt + Right / (broken Mac) |
| **Settings**                            |                                                 |        |
| Ctrl + ,                                | ⚙️ Preferences                                  | Changed from Ctrl + Shift + P |
| Ctrl + Shift + M                        | 🧠 Models                                       | No change |
| Ctrl + Shift + O                        | 💬 Options (current Chat Model)                 | No change |
| Ctrl + Shift + +                          | Increase Text Size                              | No change |
| Ctrl + Shift + -                          | Decrease Text Size                              | No change |
| Ctrl + /                                | Shortcuts                                       | Changed from Ctrl + Shift + ? (Windows) / Ctrl + Shift + / (Mac) |

**Comment by enricoros** [comment]
@mapringg Note, 2.0 will also come with a new shortcuts bar which displays the top shortcuts available in the UI.
image

**Comment by enricoros** [comment]
PR merged in 2.0.0.

**Pull request merged**
