### PR TITLE
Add Dockerfile and GitHub workflow to build and publish Docker image

### PR DESCRIPTION
**Pull request by FelixClements**
This commit adds a Dockerfile with instructions to build a Node.js application, and a GitHub workflow file to automate building and publishing a Docker image of the application to a container registry. 

The Dockerfile contains instructions to set up the Node.js environment, copy application files, and reduce installed packages to production-only. The GitHub workflow file defines a job to build and push the Docker image using Docker build and push actions, with metadata extracted using a Docker metadata action.

### CODE REVIEW

**Comment by enricoros** [comment]
Hi @FelixClements love the contrib. Would like to merge, so here are a couple of questions:
1. I am familiar with the Vercel flow (and as you see up here the Vercel bots are building everything and deploying every single commit as an install) - how would this Docker flow change/add to the existing?
2. What is the benefit of having github perform that docker-based action? <- will it do it in my repo too by default, or do I need to turn something on?
3. Finally: would you be open to add a /docs/deploy-docker.md with an explanation what it is, benefits, how-to build and serve?

I'm attaching one I created with big-AGI itself, dragging in your files, and asking the questions above.

```Markdown
# Deploy `big-AGI` with Docker 🐳

Deploy the big-AGI application using Docker containers for a consistent, efficient, and automated deployment process. Enjoy faster development cycles, easier collaboration, and seamless environment management. 🚀

Docker is a platform for developing, packaging, and deploying applications as lightweight containers, ensuring consistent behavior across environments.

## `big-AGI` Docker Components

The big-AGI repository includes a Dockerfile and a GitHub Actions workflow for building and publishing a Docker image of the application.

### Dockerfile

The Dockerfile sets up a Node.js environment, installs dependencies, and creates a production-ready version of the application.

### GitHub Actions Workflow

The `.github/workflows/docker-image.yml` file automates building and publishing the Docker image when changes are pushed to the `main` branch.

## Deploy Steps

1. Clone the big-AGI repository
2. Navigate to the project directory
3. Build the Docker image using the provided Dockerfile
4. Run the Docker container with the built image

Embrace the benefits of Docker for a reliable and efficient big-AGI deployment. 🎉
```

**Comment by FelixClements** [comment]
1: To be honest I don't know. My Vercel knowledge end at it exists and they have a website. Is there a way to check? Do you have a workflow file for Vercel or something?
2: GitHub will build and and make it available without any settings. I just added the workflow file and the image got build automatically
3: Sure, later this week I have some time to make a proper manual but this is the docker-compose file I used to spin it up on my swarm.

version: "3"
services:
  nextjs-chatgpt-app:
    image: ghcr.io/felixclements/nextjs-chatgpt-app:main
    container_name: chatgpt
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - OPENAI_API_KEY=
      - OPENAI_API_ORG_ID=
    ports:
      - 3000:3000
    restart: unless-stopped

**Comment by enricoros** [comment]
Thanks, I will test is on a branch before merging and looking forward to more information (just making sure we check all the boxes).

**Comment by enricoros** [comment]
Hi @FelixClements - there's an official Docker package being created now. Can you help testing if this works?

**Comment by FelixClements** [comment]
Hi @enricoros I replaced the image line to ghcr.io/enricoros/big-agi:main and redeployed the stack. As far as I can tell it works!

**Pull request merged**
