### PR TITLE
Add Claude 3 models

### PR DESCRIPTION
**Pull request by jacksongoode**

### CODE REVIEW

**Comment by enricoros** [comment]
@jacksongoode I've merged but there's a build error(!) can you take care of this?

**Comment by jacksongoode** [comment]
I saw that, I don't think I'm able to view the builds from my end without access via Vercel?

**Comment by enricoros** [comment]
@jacksongoode if you do "npm run build" in your local machine, you'll get the same. It's an issue on the added code (some parenthesis or similar).

**Comment by enricoros** [comment]
Screenshot_20240304_145856_Chrome
@jacksongoode this is how the error looks like (sorry on mobile, boarding a plane)

**Comment by enricoros** [comment]
@jacksongoode took care of it thanks again

**Comment by jacksongoode** [comment]
Thank you! Sorry about that, didn't think this PR would get merged so fast!

**Comment by enricoros** [comment]
@jacksongoode doesn't work yet because of an API change on the Anthropic side. This will require more work

**Pull request merged**
