### PR TITLE
MongoDB Atlas Support

### PR DESCRIPTION
**Pull request by ranfysvalle02**
MongoDB support for LinkStorage also opens up more possibilities since MongoDB Atlas now supports $vectorSearch!

MongoDB Atlas has native vector storage and search capabilities embedded in an operational database. Combine vector search with other query capabilities available in MongoDB for defining advanced filters on vector queries. It provides the functional capabilities and the scalability, reliability, and security features in a multi-cloud platform to address the needs of GenAI-powered applications - like big-AGI. 

big-AGI+MongoDB

### CODE REVIEW

**Comment by enricoros** [comment]
Thank you, this is pretty good. From a first review one issue seems to be that Mongo replaces Postgres inside the prisma.schema.
This will invalidate all the existing installations with a DB. Any solutions for that?

**Comment by ranfysvalle02** [comment]
prisma.schema can stay postgres; this can be an optional solution for anyone just doing MongoDB. Perhaps we move the changes from prisma.schema to the readme and leave prisma.schema as is? What do you think?

**Comment by ranfysvalle02** [comment]
@enricoros - I updated the repo/pull-request.... Let me know what you think, happy to change whatever needs changing... I think MongoDB Atlas will open up a whole new world of possibilities (optional of course) for big-AGI :)

**Comment by ranfysvalle02** [comment]
Will get those changes in today 👌

**Comment by ranfysvalle02** [comment]
Updated the docs -- also included why I highly recommend MongoDB Atlas versus Postgres. There are some really cool 'data platform' capabilities that can enable big-AGI in some interesting ways! HTTPS endpoints, Triggers, vector search, data federation (which let's you query non-MongoDB data sources through the MongoDB query API!) and much more! Let me know what you think -- happy to make any modifications needed.

**Comment by enricoros** [comment]
Stunning job, this is really good and needed. Big-AGI has a very large amount of custom deployments and docs are important to them.

Great quality submission - merging right away!

**Pull request merged**
