### PR TITLE
feat: add support for llama 3.1 8b and 70b for groq

### PR DESCRIPTION
**Pull request by mapringg**
Added support for LLaMA 3.1 in GROQ. Will include support for the 405b version upon its public release.

### CODE REVIEW

**Comment by enricoros** [comment]
Hi @mapringg - thanks! I literally just added it to the big-agi-2 branch. I'll go ahead and compare to your impl :)

**Comment by enricoros** [comment]
@mapringg - some info:
- thanks for the responsiveness!
- I've merged the changes queued up for big-agi-2, as there were a couple more changes (max tokens out)
- I put the same hidden models as you did - good picks :D
- apologies I didn't merge yours, but was literally over the same data (would have conflicted)
- below some insights on how I performed the change, with big-AGI-2

(do not use big-agi 2 yet! too unstable and will corrupt data)
image
(do not use big-agi 2 yet! too unstable and will corrupt data)

**Comment by mapringg** [comment]
@enricoros No problem. I use this project daily and would like to help in any way that I can.

**Comment by enricoros** [comment]
@mapringg feel a good feature that's missing and would make you more efficient - and add that. I'm here if you have any questions. I'll merge any quality code.

**Pull request closed without merging**
