### PR TITLE
Build multi-arch docker image for x64-64 and ARM64

### PR DESCRIPTION
**Pull request by mludvig**
Enable build of ARM64 image for use on MacBook with apple silicon (M1, M2, M3). It's about 3x faster than running the x86-64 container on the Apple silicon under Rosetta emulation.

### CODE REVIEW

**Comment by enricoros** [comment]
@mludvig does this replace the current images, or adds to them? This workflow is used for the official images in the project page.

**Comment by mludvig** [comment]
@enricoros It builds a multi-arch image. Technically 2 separate images, one for x86-64 and one for arm64 but both have the same name (e.g. big-agi:latest) and the correct platform is pulled based on which arch you're running on.

This won't change the existing images but the next time you release a new version a multi-arch will be created. It should be completely transparent to the users.

My test build is: ghcr.io/mludvig/big-agi:sha-7643770 - you can give it a try.

**Comment by enricoros** [comment]
Thanks, this is very useful and the explanation as well. On the nature of the change itself:
- removing the comments at the beginning?
- changing the versions of many docker images? (I read pinned versions are more secure)

**Comment by mludvig** [comment]
Using "@v5" is a bit more flexible as it may eventually get security or stability updates while being backwards compatible within the v5.x line. These versions were tested and worked for me.

But if you prefer to keep your hashes and put the comments back I can update the PR. Up to you.

**Comment by mludvig** [comment]
@enricoros I've cleaned up the unrelated changes and only left the multi-arch stuff in.

**Review by enricoros — APPROVED** [review]

**Comment by enricoros** [comment]
Thanks @mludvig - merged

**Pull request merged**
