### PR TITLE
Support Web Speech API

### PR DESCRIPTION
**Pull request by zoollcar**
1.You can choose **Elevenlabs** OR **Web Speech API** for TTS in Preferences, and choose the voice. Add some code easy to add more TTS and STT API in the future
image

2.Call function will speak when meet  **.,!?**, Make calls sound more Immersive.
image

### CODE REVIEW

**Comment by enricoros** [comment]
Thanks for this @zoollcar I'm looking into it right now, expect updates soon. The screenshots look good, I will have to review carefully because quality and robustness is of the top importance for Big-AGI. Let me know in the meantime if you have updates.

**Comment by zoollcar** [comment]
Thanks for your reply. I merged big-agi-2, solve some conflicts and fix some bugs. Now **Chat** feature looks good, but I can't test **Call** feature, because it seems haven't completed in this branch.
```
llmStreamingChatGenerate: call not migrated to AIX yet
```

**Comment by enricoros** [comment]
Thanks @zoollcar - correct, the Call feature is on me to restore. The AIX subsystem is much more powerful, and I'll prioritize the restoring of basic llm functions.

Sorry to not having reviewed and merged this weekend, I'm very busy on roadmap items, but I'll look at this soon. I will also need to see whether to have a contributors agreement (I see large projects doing that before merging patches, and I need to make sure we cover all the bases as the project will scale up rapidly).

Thanks for porting to the -2 branch - I was able to try it on both Chrome and Safari and it works well. The following feedback is just for using it, not reading the code yet:
- very quick generation, I'm really impressed
- some voices are great (e.g. some Google voices), others are terrible, I wonder if something can be done to pre-select the best for each platform (https://github.com/HadrienGardeur/web-speech-recommended-voices)
- after switching the provider to web speech, I need to reload the page for the synthesis to work (I'll look if I see any react hook issue when I review the code)
- sometimes I didn't get the audio and also didn't get any error notification; I wonder if something can be done to show the user any notification

Awesome!

**Comment by zoollcar** [comment]
Thank you for test, I'm glad to contribute.&nbsp;



```
some voices are great (e.g. some Google voices), others are terrible, I wonder if something can be done to pre-select the best for each platform (https://github.com/HadrienGardeur/web-speech-recommended-voices)
```
I'll check it out, I'm also interested in language filter. On my computer Edge browser, i have a lot of language voices in the list. I wish it can link with the language selecter above.


```
after switching the provider to web speech, I need to reload the page for the synthesis to work (I'll look if I see any react hook issue when I review the code)
sometimes I didn't get the audio and also didn't get any error notification; I wonder if something can be done to show the user any notification
```
I'll check it as soon as possible.




```
I noticed the module is modules/browser; are there better alternatives?&nbsp;
```
Yes, maybe modules/browser/speechSynthesis?


Let me know if you have any ideas, if you're confirm, I'll change it at once.


```
I am not able to cleanly rebase the code on big-agi-2 at this moment (it's okay, I see there have been merges); do you think it would be possible for you to make this a single commit on top of big-agi-2, or as alternative, would you like me to do that and commit for you?
```
Pls do that for me, I don't know how to do it and don't want make it mess.


After you done, pls let me know, how to push new path to this PR.


Thank you.

**Comment by enricoros** [comment]
Sorry if I haven't reviewed this yet; I am very busy with lots of other changes in the priority queue at the moment.

**Comment by enricoros** [comment]
@zoollcar I've manually rebased and squashed the comments, so they'll apply cleanly to the big-agi-2 branch (the only branch that matters now).

Here's the issue: I will have to cleanup the patch, there are some parts of it that are great, some others that cannot be landed in the proejct (e.g. run.bat doesn't belong) and others where I need to find different solutions.

I can do all the fixes and land this quickly in the code, however GitHub may not give you the full credit (and probalby won't close the PR). Let me know if you want me to proceed and land this feature after a cleanup -- otherwise I can tell you about the rebases and the files to remove, but right now could be a mess to do the rebase and prob need a new PR after.

Please let me know if you want me to land this feature as a single commit on `big-agi-2`. If so, I'll proceed with a review.

image

image

**Comment by zoollcar** [comment]
1. if you want me to land this feature as a single commit on big-agi-2. If so, I'll proceed with a review.
I tried do the clean up, there it is https://github.com/zoollcar/big-AGI/tree/Browser-TTS-for-version2
Is that OK? If so, I'll make a new PR and close this. If not, pls land this feature as a single commit.

2. if there is anything incomplete in this feature or possible technical issues (e.g. crashes) I should be aware of.
Yes, There are a few:
    1. I can't reproduce the bug you showed, but it may be related to git submodules.
    1. When switching the TTS engine, the Elecenlabs test voice doesn't stop when I switch to the Web Speech API.
    2. The Web Speech API test sentence is from the `web-speech-recommended-voices` project and contains a placeholder {name}. I haven't found a good solution for this
    4. In dev mode, some times, after I switch TTS engine and change to Call page, it  crashed. can't reproduce for now.
    5. Using a Git submodule might not be the best solution.
    6. Some languages ​​have very few voices. pre-select will causing the voice list to become empty. Perhaps we should hide the pre-select option in these cases.

**Comment by enricoros** [comment]
What you have is much better, very good job. I appreciate that you removed the run.bat and alike.

Is is possible to remove the submodule dependency (the Big-AGI downstream projects won't appreciate, and I also am worried about what happens if anything changes in the upstream project) and instead have a local copy of en.json or the others? The very best way would be to load the file directly from GitHub, so Big-AGI doesn't get larger at all.

Then please go ahead and open a PR to the `big-agi-2` branch, and I'll take a closer look. My time is really scarce right now, so could take some time, but I appreciate how you increased the quality of the patch.

**Pull request closed without merging**
